Update patch set 1
Patch Set 1:

Perhaps I am missing something, but this commit indeed breaks the build for TARGET_OMAP3 and OMAP_ENHANCEMENT:

target thumb C++: libaudiopolicybase <= frameworks/base/services/audioflinger/AudioPolicyManagerBase.cpp
frameworks/base/services/audioflinger/AudioPolicyService.cpp: In static member function 'static void android::AudioPolicyService::instantiate()':
frameworks/base/services/audioflinger/AudioPolicyService.cpp:485: error: cannot allocate an object of abstract type 'android::AudioPolicyService'
frameworks/base/services/audioflinger/AudioPolicyService.h:33: note:   because the following virtual functions are pure within 'android::AudioPolicyService':
hardware/libhardware_legacy/include/hardware_legacy/AudioPolicyInterface.h:202: note:   virtual android::status_t android::AudioPolicyClientInterface::setFMRxActive(bool)

Suggested fix: Replace OMAP_ENHANCEMENT by OMAP_ENHANCEMENT && TARGET_OMAP4 (or fix frameworks/base).

Patch-set: 1